Add check for receipt value
graphprotocol/indexer-rs pull request #164
Opened 2024-05-10 18:08 UTC by carlosvdr

issue #145

2024-05-10 19:27 UTC, gusinacio requested changes

2024-05-10 19:27 UTC, gusinacio commented on common/src/tap/checks/receipt_max_val_check.rs
> +                "Receipt vallue `{}` is higher than the limit set by the user",
typo

2024-05-10 19:27 UTC, gusinacio commented on common/src/tap/checks/receipt_max_val_check.rs
> +    }
These tests are useful to check functionality but tests around limits are more useful to maintain behavior. Add tests to:
- value = limit - 1
- value = limit
- value = limit + 1

2024-05-10 21:06 UTC, aasseman approved these changes

2024-05-13 19:14 UTC, aasseman approved these changes

2024-05-13 19:15 UTC, merged