fix(tap-agent): allow sender on allocation close
graphprotocol/indexer-rs pull request #254
Opened 2024-07-24 20:20 UTC by gusinacio

2024-07-24 21:59 UTC, aasseman requested changes
LGTM, just a couple of typos

2024-07-24 21:59 UTC, aasseman commented on tap-agent/src/agent/sender_account.rs
> +    HasSchedulerEnabled(ractor::RpcReplyPort<bool>),
```suggestion
    IsSchedulerEnabled(ractor::RpcReplyPort<bool>),
```
or
```suggestion
    HasScheduler(ractor::RpcReplyPort<bool>),
```

2024-07-24 21:59 UTC, aasseman commented on tap-agent/src/agent/sender_account.rs
> +        let scheuduler_enabled =
```suggestion
        let scheduler_enabled =
```

2024-07-25 16:59 UTC, gusinacio commented on tap-agent/src/agent/sender_account.rs
> +        let scheuduler_enabled =
Done

2024-07-25 16:59 UTC, gusinacio commented on tap-agent/src/agent/sender_account.rs
> +    HasSchedulerEnabled(ractor::RpcReplyPort<bool>),
Done

2024-07-25 17:27 UTC, aasseman approved these changes

2024-07-25 17:27 UTC, merged