fix(tap-agent): maintain backoff information
graphprotocol/indexer-rs pull request #283
Opened 2024-08-09 12:19 UTC by gusinacio

2024-08-12 20:35 UTC, aasseman requested changes
LGTM
Just a little fix on a log output

2024-08-12 20:35 UTC, aasseman commented on tap-agent/src/agent/sender_allocation.rs
> +                            "Cann't trigger rav request until {:?}",
```suggestion
                            "Can't trigger rav request until {:?} (backoff)",
```

2024-08-12 21:06 UTC, gusinacio commented on tap-agent/src/agent/sender_allocation.rs
> +                            "Cann't trigger rav request until {:?}",
Done

2024-08-13 09:39 UTC, aasseman approved these changes

2024-08-13 12:35 UTC, merged