fix: add warn where trigger_value is below 0.1 grt
graphprotocol/indexer-rs pull request #340
Opened 2024-10-02 21:47 UTC by carlosvdr

fixes #323

2024-10-03 10:42 UTC, gusinacio requested changes

2024-10-03 10:42 UTC, gusinacio commented on config/src/config.rs
> +                allocation not returning any receipts.
The message could be: the system may constantly deny the sender.

2024-10-03 10:42 UTC, gusinacio commented on config/src/config.rs
> +                "Trigger value is too low,currently below 0.1 GRT. \
typo, space between comma and next letter

2024-10-03 10:42 UTC, gusinacio commented on config/src/config.rs
> +                To have a higher trigger value, ideally above 1 GRT \
could you review the punctuation and capitalization of letters?

2024-10-03 10:47 UTC, gusinacio commented
Also, technically this is a feature. We are not fixing something that is broken, we are adding an alert functionality.

2024-10-03 23:01 UTC, carlosvdr commented
Hmm i dont like it being a feature but its closer to that rather than a fix yes

2024-10-04 08:00 UTC, gusinacio approved these changes
LGTM

2024-10-04 08:00 UTC, merged