Use config crate for service
graphprotocol/indexer-rs pull request #409
Opened 2024-10-25 16:27 UTC by Shiyasmohd

This PR closes #402 

Changes in this PR
- Updated imports in `indexer_service.rs` & `service/src/service.rs`
- Delete `config.rs` from `common/indexer-service` & `service`
- Added a fn to get as `SocketAddr` from `MetricsConfig`

2024-10-25 18:18 UTC, gusinacio requested changes
This is great code! 

In general, I'd like to remove those conversions and use proper types til the last minute. 
`indexer_config` already does a lot of validation and conversion while parsing the config to give you the correct types, let's not convert multiple times.

2024-10-25 18:18 UTC, gusinacio commented on service/src/service.rs
> -    let config = MainConfig::parse(indexer_config::ConfigPrefix::Service, cli.config.as_ref())
Hey, I think you can `Box::leak` the configuration, that way you don't need to clone things.

2024-10-25 18:18 UTC, gusinacio commented on service/src/service.rs
> +        graph_node_query_base_url: config.graph_node.query_url.clone().to_string(),
You could convert this into `Url`

2024-10-25 18:18 UTC, gusinacio commented on common/src/indexer_service/http/indexer_service.rs
> +                    .as_secs(),
syncing_interval is already a `Duration`

2024-10-25 18:18 UTC, gusinacio commented on common/src/indexer_service/http/indexer_service.rs
> +                    .as_secs(),
recently_closed_allocatin_buffer_secs is already a `Duration`

2024-10-25 18:18 UTC, gusinacio commented on common/src/indexer_service/http/indexer_service.rs
>              dispute_manager,
You could update `attestation_signers` to receive a `Mnemonic`

2024-10-25 18:18 UTC, gusinacio commented on common/src/indexer_service/http/indexer_service.rs
> +            }),
wonderful

2024-10-25 18:18 UTC, gusinacio commented on common/src/indexer_service/http/indexer_service.rs
> +            ),
syncing_interval is already a `Duration`

2024-10-25 18:18 UTC, gusinacio commented on common/src/indexer_service/http/indexer_service.rs
Already `Duration`.

2024-10-25 18:18 UTC, gusinacio commented on common/src/indexer_service/http/indexer_service.rs
> +            serde_json::json!({ "publicKey": public_key(&options.config.indexer.operator_mnemonic.to_string())?}),
Maybe update `public_key` to receive Mnemonic

2024-10-25 18:18 UTC, gusinacio commented on config/src/config.rs
> +}
nice

2024-10-26 13:56 UTC, shiyasmohd commented
Hey @gusinacio ,
Thanks for the feedback. I've made necessary changes.
I've also refactored some lines in [this](https://github.com/graphprotocol/indexer-rs/pull/409/commits/c0358bb24d3c238356fdfc7804848880ea32c440#diff-2173e0a1ff7c183bf7d8e97977ffddd00ac5e3ccc45b8d1d3c59723c90fa258c) commit. 

Please let me know your thoughts.

2024-10-26 16:13 UTC, gusinacio submitted a review, later dismissed
LGTM, thank you for your beautiful code!

2024-10-26 21:36 UTC, gusinacio approved these changes

2024-10-28 17:05 UTC, merged