feat: add graph-indexed header in subgraph query response
graphprotocol/indexer-rs pull request #522
Opened 2024-12-01 16:11 UTC by shiyasmohd

Fixes #494

2024-12-03 17:02 UTC, Theodus approved these changes
I literally implemented this just now assuming no one did it yet, and it looks the same. So I'll give this an approval :+1:

2024-12-03 17:50 UTC, Theodus requested changes

2024-12-03 17:50 UTC, Theodus commented on crates/service/src/routes/request_handler.rs
> +    let graph_indexed = response.headers().get(GRAPH_INDEXED).cloned();
This line needs to be moved above where `let mut response = Response::new(body);` aliases `response` away from the graph-node response.

2024-12-04 14:35 UTC, shiyasmohd commented
@Theodus Thanks for the review. Pushed the changes

2024-12-04 14:45 UTC, Theodus approved these changes

2024-12-04 14:46 UTC, merged