fix: graph-node-status-endpoint for DeploymentDetail status_url
graphprotocol/indexer-rs pull request #91
Opened 2023-11-08 18:53 UTC by hopeyen

Indexer service takes in 
```
graph_node_query_endpoint // commonly 'http://localhost:8000'
graph_node_status_endpoint // commonly 'http://localhost:8030/graphql'
```

`DeploymentDetails::for_graph_node` currently generalized `graph_node_base_url` for both 
- `status_url` by appending `/status`
- `query_url` by appending `/subgraphs/id/:id`

I made updates to use the configured `--graph-node-status-endpoint` for `status_url` instead of `graph_node_query_endpoint`.

2023-11-08 20:20 UTC, Theodus approved these changes
Thanks! I've confirmed this is now working as expected on the local-network

2023-11-08 20:37 UTC, aasseman requested changes
There may be an issue with the tests though. I restarted the job to see if it was a fluke.

2023-11-08 20:52 UTC, aasseman commented
There's definitely an issue with the tests:
```
test subgraph_client::client::test::test_uses_local_deployment_if_healthy_and_synced has been running for over 60 seconds
test subgraph_client::client::test::test_uses_query_url_if_local_deployment_is_not_synced has been running for over 60 seconds
```
@hopeyen could you try running the tests locally and see what happens?

2023-11-10 01:59 UTC, aasseman approved these changes

2023-11-10 04:46 UTC, merged